#include "RAII.h"
#include "standard_fix.h"
// dummy deleter, placeholder to silent the warning generated by RAII_delete
static void RAII_dummy_deleter_(Unused void* target_){}
void RAII_set_deleter(void* target_, void(*deleter)(void* target_)){
    RAII* target = (RAII*)target_;
    target->deleter = deleter;
}
void RAII_set_dummy_deleter(void* target_){
    RAII_set_deleter(target_, RAII_dummy_deleter_);
}
void RAII_delete(void* target_){
    RAII* target = (RAII*)target_;
    if(target->deleter != NULL) target->deleter(target_);
    else{
        #ifndef NDEBUG
        fprintf(stderr, "Freeing a RAII embedded object with no deleter set!\n");
        #endif
    }
    free(target_);
}